---
title: Summary of results for `r obsFolder`
output: pdf_document
keep_tex:  false
date: \today
geometry: "left=2.5cm,right=2.5cm,top=2cm,bottom=2cm"
---

<!-- # ```{r test } -->
<!-- # getwd() -->
<!-- # obsFolder <- "GBM_alpha_1_sigma_2_x0_100" -->
<!-- # M <- 10 -->
<!-- # m <- 1 -->
<!-- # ``` -->


```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(knitr.duplicate.label = 'allow')
library(stringr)

total_missing <- 0
total_missing_stan <- 0

N <- 100
model_type <- substr(obsFolder,1,3)
if(model_type == "GBM"){
  par_names <- c("alpha", "sigma2")
}else if(model_type == "CIR"){
  par_names <- c("beta", "sigma2")
}

if(obsFolder == "GBM_alpha_1_sigma_2_x0_100"){
  true_values <- c(1,2)
}else if(obsFolder == "CIR_alpha_1_beta_1_sigma_0.25_x0_3" ){
 true_values <- c(1,0.25)
}else if(obsFolder == "CIR_alpha_1_beta_1_sigma_2_x0_10"){
 true_values <- c(1,2)
}
```

<!-- ```{bash, echo=TRUE} -->
<!-- echo $PWD -->
<!-- cat tests/missing_GBM_alpha_1_sigma_2_x0_100.txt | grep 'Euler\|Milstein ' | cut -d " " -f 2-5 | sort |uniq -c | sort -nr -->
<!-- ``` -->

```{r functions, echo=FALSE}
load_aggregated_output <- function(obsFolder, M, m){
  # loads the aggregated output of the different MCMC methods and stores them in multidim. arrays
  folder_name <- paste("simulation_study/", obsFolder, "/aggregated_output/", sep = "")
  # determine the relevant aggregated_output files
  all_file_names <- list.files(path = folder_name)
  fileName_fragment <-  paste("M_", M, "_m_", m, sep = "")
  file_names <- all_file_names %>% str_subset(fileName_fragment)
  
  num_methods <- length(file_names)
  method_names_long <- sub("^(.[^_]*_+){6}", "", word(file_names, 1, -2, sep = fixed(".data")))
  method_names <- gsub("Milstein", "M", gsub("Euler", "E", method_names_long))
  
  cnames_separate <- c("mean", "median", "variance", "hpd_low", "hpd_up", "ESS_coda", "mode")
  ncol_separate <- length(cnames_separate)
  cnames_overall <- c("numIterations", "multivarESS", "Duration", "ARpath", 
                      "ARparam", "covariance", "nNegPointProposals", "nMBSwitchToEuler")
  ncol_overall <- length(cnames_overall)
  
  results_separate_all <-
    array(rep(NA, length = N * ncol_separate * length(par_names) * num_methods),
          dim = c(N, ncol_separate, length(par_names), num_methods),
          dimnames = list(path_index = 1:N,
                          results = cnames_separate,
                          parameter = par_names,
                          method = method_names))

  resultsOverall_all <- array(rep(NA, length = N * ncol_overall * num_methods),
                          dim = c(N, ncol_overall, num_methods),
                          dimnames = list(path_index = 1:N, 
                                          results = cnames_overall, 
                                          method = method_names))
  for (i in 1:num_methods){
  try(load(paste(folder_name, file_names[i] ,sep = "")))
    results_separate_all[ , , , i] <- results_separate
    resultsOverall_all[ , , i] <- resultsOverall
  }
 return(list(results_separate_all = results_separate_all, 
             resultsOverall_all = resultsOverall_all))
}

load_aggregated_Stan_output <- function(obsFolder, M){
  folder_name <- paste("simulation_study/", obsFolder, "/aggregated_output/", sep = "")
  try(load(paste(folder_name, "true_posterior_M_", M, ".data" ,sep = "")))
  # contains: results_separate and resultsOverall
  return(list(results_separate_Stan = results_separate, 
             resultsOverall_Stan = resultsOverall))
}

```

`r M=10`
```{r M_10, echo=FALSE, results='asis'}
res <- knitr::knit_child('template_summary_section_M.Rmd', 
                          quiet = TRUE)
cat(unlist(res), sep = '\n')
```
\newpage
`r M=20`
```{r M_20, echo=FALSE, results='asis'}
res <- knitr::knit_child('template_summary_section_M.Rmd',
                          quiet = TRUE)
cat(unlist(res), sep = '\n')
```
\newpage
`r M=50`
```{r M_50, echo=FALSE, results='asis'}
res <- knitr::knit_child('template_summary_section_M.Rmd',
                          quiet = TRUE)
cat(unlist(res), sep = '\n')
```

# # of missing results: `r total_missing`


\newpage
# Stan results (sampling from and optimizing the true posterior)

`r M=10`
```{r Stan_M_10, echo=FALSE, results='asis'}
res <- knitr::knit_child('template_summary_Stan_section_M.Rmd', quiet = TRUE)
cat(unlist(res), sep = '\n')
```

\newpage
`r M=20`
```{r Stan_M_20, echo=FALSE, results='asis'}
res <- knitr::knit_child('template_summary_Stan_section_M.Rmd', quiet = TRUE)
cat(unlist(res), sep = '\n')
```

\newpage
`r M=50`
```{r Stan_M_50, echo=FALSE, results='asis'}
res <- knitr::knit_child('template_summary_Stan_section_M.Rmd', quiet = TRUE)
cat(unlist(res), sep = '\n')
```


# # of missing Stan results: `r total_missing_stan`