## M =  `r M`


### Density plots of discrepancies

```{r, comment=NA, fig.width=8, fig.height=5}
v_m <- c(1, 2,5) 

folder_name <- paste0("simulation_study/", obsFolder, "/aggregated_output/")
file_names <- list.files(path = folder_name)

results <- c("mean", "median", "variance")
num_res <- length(results)

aggregated_discr_plots <- function(obsFolder, M, m, param_index, xlim){
  # loads the aggregated output of the different MCMC methods and stores them in multidim. arrays
  folder_name <- paste("simulation_study/", obsFolder, "/aggregated_output/", sep = "")
  # determine the relevant aggregated_output files
  all_file_names <- list.files(path = folder_name)
  fileName_fragment <-  paste("M_", M, "_m_", m, sep = "")
  file_names <- all_file_names %>% str_subset(fileName_fragment)
  
  num_methods <- length(file_names)
  method_names_long <- sub("^(.[^_]*_+){6}", "", word(file_names, 1, -2, sep = fixed(".data")))
  method_names <- gsub("Milstein", "M", gsub("Euler", "E", method_names_long))
  
  cnames_separate <- c("mean", "median", "variance", "hpd_low", "hpd_up", "ESS_coda", "mode")
  ncol_separate <- length(cnames_separate)
  cnames_overall <- c("numIterations", "multivarESS", "Duration", "ARpath", 
                      "ARparam", "covariance", "nNegPointProposals", "nMBSwitchToEuler")
  ncol_overall <- length(cnames_overall)
  
  results_separate_all <-
    array(rep(NA, length = N * ncol_separate * length(par_names) * num_methods),
          dim = c(N, ncol_separate, length(par_names), num_methods),
          dimnames = list(path_index = 1:N,
                          results = cnames_separate,
                          parameter = par_names,
                          method = method_names))
  
  resultsOverall_all <- array(rep(NA, length = N * ncol_overall * num_methods),
                              dim = c(N, ncol_overall, num_methods),
                              dimnames = list(path_index = 1:N, 
                                              results = cnames_overall, 
                                              method = method_names))
  for (i in 1:num_methods){
    try(load(paste(folder_name, file_names[i] ,sep = "")))
    results_separate_all[ , , , i] <- results_separate
    resultsOverall_all[ , , i] <- resultsOverall
  }
  
  # load Stan aggregated output
  try(load(paste(folder_name, "true_posterior_M_", M, ".data" ,sep = "")))
  # contains: results_separate and resultsOverall
  
  plot_discrep <- function(discrepancy, main, result, xlim){
    # estimate density for each method with the same bandwidth
    bandwidths <- apply(discrepancy, 2, function(x) density(x, na.rm = TRUE)$bw)
    bw <- mean(bandwidths)#mean(bandwidths) # or RMS: sqrt(sum(bandwidths ^ 2) / length(bandwidths))
    densities <- apply(discrepancy, 2, function(x) density(x, na.rm = TRUE, bw = bw))
    x_range <- range(unlist(lapply(densities, function(x) x[["x"]])))
    y_range <- range(unlist(lapply(densities, function(x) x[["y"]])))
    
    if(m > 1){
      v_col <- c(2,1,3,4)
      v_lty <- c(4,2,3, 1)
    }else{
      v_col <- c(1,4)
      v_lty <- c(2,1)
    }
    
    # plot the densities of the diffferent methods in the same window
    plot(NULL, xlim = xlim[[result]], ylim = y_range*1.1, main = '', xlab = '', las = 1, ann = FALSE)
    if(m == 1){
      title(main = main, cex.main = 1.4, line = 1.8, font = 2)
    }
    title(xlab = "Deviation", cex.lab = 1, line = 2.2)
    if(result == "mean"){
      title(ylab = paste0("m = ", m), cex.lab = 1.4, line = 3, font = 2, las = 1)
    }
    num_methods <- length(densities)

    for(l in 1:num_methods){
      lines(densities[[l]], col = v_col[l], lty = v_lty[l], xlim = xlim[[result]])
    }
    return(densities)
  }
  
  for(k in 1:num_res){
    # calculate discrepancy between statistic of sample from approximate posterior and
    # and statistic of sample from true posterior (Stan sample)
    res_mat <- results_separate_all[ , results[k], param_index, ]
    res_Stan <- as.vector(results_separate[, results[k], param_index])
    discrepancy <- sweep(res_mat, MARGIN = 1, res_Stan)
    if(param_index == 1){
      if(model_type == "GBM"){
        main <- bquote(Posterior ~ .(results[k]) ~ alpha)
      }else if(model_type == "CIR"){
        main <- bquote(Posterior ~ .(results[k]) ~ beta)
      }
    }else if (param_index == 2){
      main <- bquote(Posterior ~ .(results[k]) ~ sigma^2)
    }
    
    densities <- plot_discrep(discrepancy, 
                              main, 
                              results[k], xlim)
  }
  par(xpd=TRUE) # for legend outside plot region
  plot.new()
  if(m > 1){
    order <- c(2, 3, 4, 1)
    #leg_names <- names(densities)[order]
    leg_names <- c("MBE-E", "MBE-M", "MBM-M", "DBM-M")
    v_col <- c(2,1,3,4)[order]
    v_lty <- c(4,2,3, 1)[order]
  }else{
    leg_names <- c("Euler", "Milstein")
    v_col <- c(1,4)
    v_lty <- c(2,1)
  }
  legend("topleft", legend = leg_names, 
         col = v_col, lty = v_lty,
         bty = "n", cex = 1, seg.len = 2, inset=c(-5.2,0))
  par(xpd=FALSE)
  mtext(paste0("Based on up\n to ", sum(!(is.na(discrepancy[,1]))), " results."), 
        at = -2, side = 1, cex = .7)
}



#------plots alpha-------------------------------------------------------------------
if(model_type == "GBM"){
  xlim <- list(mean = c(-2,1), median = c(-2,1), variance = c(-3,1))
}else if(model_type == "CIR"){
  xlim <- list(mean = c(-.08,.08), median = c(-.06,.06), variance = c(-.2,.2))
}

par(mar=c(3.1, 4.5, 2.6, 1))
layout(matrix(1:((num_res + 1)*length(v_m)), ncol = num_res + 1, byrow = TRUE),
       widths = c(rep.int(1, num_res), .35))

for(i in 1:length(v_m)){
  aggregated_discr_plots(obsFolder, M, m = v_m[i], param_index = 1, xlim)
}

cat(" \n \n")
#------plots sigma2-------------------------------------------------------------------
if(model_type == "GBM"){
  xlim <- list(mean = c(-.7,.7), median = c(-.7,.7), variance = c(-0.4,.4))
}else if(model_type == "CIR"){
  if(true_values[2] == 2){
    xlim <- list(mean = c(-.3,.1), median = c(-.3,.1), variance = c(-.3,.15))
  }else{
    xlim <- list(mean = c(-.05,.05), median = c(-.05,.05), variance = c(-.05,.05))
  }
}

par(mar=c(3.1, 4.5, 2.6, 1))
layout(matrix(1:((num_res + 1)*length(v_m)), ncol = num_res + 1, byrow = TRUE),
       widths = c(rep.int(1, num_res), .35))

for(i in 1:length(v_m)){
  aggregated_discr_plots(obsFolder, M, m = v_m[i], param_index = 2, xlim)
}


```



\newpage
### Table of RMSE
```{r}

v_m <- c(1, 2,5) 

folder_name <- paste0("simulation_study/", obsFolder, "/aggregated_output/")
file_names <- list.files(path = folder_name)

N <- 100
model_type <- substr(obsFolder,1,3)
if(model_type == "GBM"){
  par_names <- c("alpha", "sigma2")
}else if(model_type == "CIR"){
  par_names <- c("beta", "sigma2")
}
aggregated_RMSE_matrix <- function(obsFolder, M, m){
  # loads the aggregated output of the different MCMC methods and stores them in multidim. arrays
  folder_name <- paste("simulation_study/", obsFolder, "/aggregated_output/", sep = "")
  # determine the relevant aggregated_output files
  all_file_names <- list.files(path = folder_name)
  fileName_fragment <-  paste("M_", M, "_m_", m, sep = "")
  file_names <- all_file_names %>% str_subset(fileName_fragment)
  
  num_methods <- length(file_names)
  method_names_long <- sub("^(.[^_]*_+){6}", "", word(file_names, 1, -2, sep = fixed(".data")))
  method_names <- gsub("Milstein", "M", gsub("Euler", "E", method_names_long))
  
  cnames_separate <- c("mean", "median", "variance", "hpd_low", "hpd_up", "ESS_coda", "mode")
  ncol_separate <- length(cnames_separate)
  cnames_overall <- c("numIterations", "multivarESS", "Duration", "ARpath", 
                      "ARparam", "covariance", "nNegPointProposals", "nMBSwitchToEuler")
  ncol_overall <- length(cnames_overall)
  
  results_separate_all <-
    array(rep(NA, length = N * ncol_separate * length(par_names) * num_methods),
          dim = c(N, ncol_separate, length(par_names), num_methods),
          dimnames = list(path_index = 1:N,
                          results = cnames_separate,
                          parameter = par_names,
                          method = method_names))
  
  resultsOverall_all <- array(rep(NA, length = N * ncol_overall * num_methods),
                              dim = c(N, ncol_overall, num_methods),
                              dimnames = list(path_index = 1:N, 
                                              results = cnames_overall, 
                                              method = method_names))
  for (i in 1:num_methods){
    try(load(paste(folder_name, file_names[i] ,sep = "")))
    results_separate_all[ , , , i] <- results_separate
    resultsOverall_all[ , , i] <- resultsOverall
  }
  
  # load Stan aggregated output
  try(load(paste(folder_name, "true_posterior_M_", M, ".data" ,sep = "")))
  # contains: results_separate and resultsOverall
  
  results <- c("mean", "median", "variance")
  num_res <- length(results)
  num_par <- length(par_names)
  mat_RMSE <- matrix(rep(NA, length = num_par * num_methods * num_res), 
                     ncol = num_par * num_res)
  colnames(mat_RMSE) <- apply(as.matrix(expand.grid(results,par_names)), 
                              1, paste0, collapse = "_")
  rownames(mat_RMSE) <- dimnames(results_separate_all)[[4]]
  
  for(k in 1:num_res){
    for(i in 1:num_par){
      # calculate discrepancy between statistic of sample from approximate posterior and
      # and statistic of sample from true posterior (Stan sample)
      res_mat <- results_separate_all[ , results[k], i, ]
      res_Stan <- as.vector(results_separate[, results[k], i])
      discrepancy <- sweep(res_mat, MARGIN = 1, res_Stan)
      mat_RMSE[ ,(i-1) * num_res + k] <- apply(discrepancy, 2, function(x) sqrt(mean(x^2, na.rm = TRUE)))
    }
  }
  
  if(m > 1){
    method_order <- c("MB_td_E_pd_E", "MB_td_M_pd_E",  "MB_td_M_pd_M", "DBM_td_M_pd_M")
    new_names <- c("MBE-E", "MBE-M", "MBM-M", "DBM-M")
  }else{
    method_order <- c("td_E",  "td_M")
    new_names <- c("Euler", "Milstein")
  }
  mat_RMSE <- mat_RMSE[method_order, ]
  rownames(mat_RMSE) <- paste0(new_names, "_m_", m)
  return(mat_RMSE)
}

mat_RMSE <- NULL

for(m in v_m){
  mat <- aggregated_RMSE_matrix(obsFolder = obsFolder, M = M, m = m)
  mat_RMSE <- rbind(mat_RMSE, mat)
}


knitr::kable(mat_RMSE, digits = 3)
# %>% 
#   kable_styling(latex_options="scale_down")
```

### Table of performance measures

```{r, comment=NA}
v_m <- c(1,2,5) 

folder_name <- paste0("simulation_study/", obsFolder, "/aggregated_output/")
file_names <- list.files(path = folder_name)

N <- 100

aggregated_performance_matrix <- function(obsFolder, M, m){
  # loads the aggregated output of the different MCMC methods and stores them in multidim. arrays
  folder_name <- paste("simulation_study/", obsFolder, "/aggregated_output/", sep = "")
  # determine the relevant aggregated_output files
  all_file_names <- list.files(path = folder_name)
  fileName_fragment <-  paste("M_", M, "_m_", m, sep = "")
  file_names <- all_file_names %>% str_subset(fileName_fragment)
  
  num_methods <- length(file_names)
  method_names_long <- sub("^(.[^_]*_+){6}", "", word(file_names, 1, -2, sep = fixed(".data")))
  method_names <- gsub("Milstein", "M", gsub("Euler", "E", method_names_long))
  
  cnames_overall <- c("numIterations", "multivarESS", "Duration", "ARpath", 
                      "ARparam", "covariance", "nNegPointProposals", "nMBSwitchToEuler")
  ncol_overall <- length(cnames_overall)
  
  resultsOverall_all <- array(rep(NA, length = N * ncol_overall * num_methods),
                              dim = c(N, ncol_overall, num_methods),
                              dimnames = list(path_index = 1:N, 
                                              results = cnames_overall, 
                                              method = method_names))
  for (i in 1:num_methods){
    try(load(paste(folder_name, file_names[i] ,sep = "")))
    resultsOverall_all[ , , i] <- resultsOverall
  }
  
  measures <-  c("numIterations", "multivarESS", "ARparam", "ARpath")
  measure_array <- resultsOverall_all[ , measures, ]
  
  
  mat_mean_measures <- apply(measure_array, 2:3, mean, na.rm = TRUE)
  rownames(mat_mean_measures) <- paste0(rownames(mat_mean_measures), "_mean")
  mat_sd_measures <- apply(measure_array, 2:3, sd, na.rm = TRUE)
  mat_cv_measures <- apply(measure_array, 2:3, sd, na.rm = TRUE) / mat_mean_measures
  #rownames(mat_sd_measures) <- paste0(rownames(mat_sd_measures), "_sd")
  rownames(mat_cv_measures) <- paste0(rownames(mat_cv_measures), "_cv")
  
  mat_measures <- rbind(mat_mean_measures, mat_cv_measures)
  num_measures <- length(measures)
  new_order <- rep(c(0,num_measures), times = num_measures) + rep(1:num_measures, each = 2)
  if(m > 1){
    method_order <- c("MB_td_E_pd_E", "MB_td_M_pd_E",  "MB_td_M_pd_M", "DBM_td_M_pd_M")
    new_names <- c("MBE-E", "MBE-M", "MBM-M", "DBM-M")
  }else{
    method_order <- c("td_E",  "td_M")
    new_names <- c("Euler", "Milstein")
    mat_measures[c("ARpath_mean", "ARpath_cv"), ] <- NA
  }
  mat_measures <- t(mat_measures[new_order, method_order])
  rownames(mat_measures) <- paste0(new_names, "_m_", m)
  return(mat_measures)
}


performance_mat <- NULL
for(m in v_m){
  mat <- aggregated_performance_matrix(obsFolder = obsFolder, M = M, m = m)
  performance_mat <- rbind(performance_mat, mat)
}

colnames(performance_mat) <- c("numIter_mean", "numIter_cv", "multESS_mean", 
                               "multESS_cv", "ARpath_mean", "ARpath_cv", 
                               "ARparam_mean", "ARparam_cv")

knitr::kable(performance_mat[,1:4], digits = c(0,2,0,2))
knitr::kable(performance_mat[,5:8], digits = c(3,2,3,2))

cat(" \n \n")
```

\newpage
### Parameter correlations

```{r , fig.width=8, fig.height=1.6, message=FALSE, warning=FALSE, error=FALSE}

folderName <- paste('simulation_study/', obsFolder, "/output/Stan/", sep = "")

num_plots <- 5
indices_2d_dens_plots <- (1:num_plots) * floor(N / num_plots)

# 2d-density plots of the parameter sample from the true posterior -------------------

# Multiple plot function
#
# copied from : http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


plots <- list()
for(k in 1:length(indices_2d_dens_plots)){
  file_name <- paste("stanfit_objects/stanfit_object_", "M_", M, "_path_", indices_2d_dens_plots[k],
                     ".rds", sep = "")
  stanfit_object <- try(readRDS(paste(folderName, file_name, sep = "")))
  if(class(stanfit_object)!= "try-error"){
    res <- as.data.frame(stanfit_object)
    # Show the contour only
    p <- ggplot(res, aes_string(x=par_names[1], y=par_names[2])) +
      geom_density_2d()+
      theme(plot.margin = unit(c(0.2,0.1,0.1,0.3), "lines")) +
      ggtitle(paste("path no.", indices_2d_dens_plots[k])) + 
      theme(plot.title = element_text(size = 10, hjust = 0.5, vjust = .5),
            axis.title.y = element_text(angle = 0, vjust = 0.5)) +
      labs(x = par_labels[1], y = par_labels[2])

    plots[[k]] <- p
  }
}

multiplot(plotlist = plots, cols = 5)

```

```{r, fig.width=7, fig.height=3}
# histograms of parameter correlations -----------------------------------------------
aggregated_correlations <- function(obsFolder, M, m){
  # loads the aggregated output of the different MCMC methods and stores them in multidim. arrays
  folder_name <- paste("simulation_study/", obsFolder, "/aggregated_output/", sep = "")
  # determine the relevant aggregated_output files
  all_file_names <- list.files(path = folder_name)
  fileName_fragment <-  paste("M_", M, "_m_", m, sep = "")
  file_names <- all_file_names %>% str_subset(fileName_fragment)
  
  num_methods <- length(file_names)
  method_names_long <- sub("^(.[^_]*_+){6}", "", word(file_names, 1, -2, sep = fixed(".data")))
  method_names <- gsub("Milstein", "M", gsub("Euler", "E", method_names_long))
  
  cnames_separate <- c("mean", "median", "variance", "hpd_low", "hpd_up", "ESS_coda", "mode")
  ncol_separate <- length(cnames_separate)
  cnames_overall <- c("numIterations", "multivarESS", "Duration", "ARpath", 
                      "ARparam", "covariance", "nNegPointProposals", "nMBSwitchToEuler")
  ncol_overall <- length(cnames_overall)
  
  results_separate_all <-
    array(rep(NA, length = N * ncol_separate * length(par_names) * num_methods),
          dim = c(N, ncol_separate, length(par_names), num_methods),
          dimnames = list(path_index = 1:N,
                          results = cnames_separate,
                          parameter = par_names,
                          method = method_names))
  
  resultsOverall_all <- array(rep(NA, length = N * ncol_overall * num_methods),
                              dim = c(N, ncol_overall, num_methods),
                              dimnames = list(path_index = 1:N, 
                                              results = cnames_overall, 
                                              method = method_names))
  # load aggregated output for the different methods
  for (i in 1:num_methods){
    try(load(paste(folder_name, file_names[i] ,sep = "")))
    results_separate_all[ , , , i] <- results_separate
    resultsOverall_all[ , , i] <- resultsOverall
  }
  
  # load Stan aggregated output
  try(load(paste(folder_name, "true_posterior_M_", M, ".data" ,sep = "")))
  # contains: results_separate and resultsOverall
  
  
  correlation_mat <- matrix(rep(NA, N * (num_methods + 1)), ncol = num_methods + 1 )
  if(m > 1){
    method_order <- c("MB_td_E_pd_E", "MB_td_M_pd_E",  "MB_td_M_pd_M", "DBM_td_M_pd_M")
    new_names <- c("MBE-E", "MBE-M", "MBM-M", "DBM-M")
  }else{
    method_order <- c("td_E",  "td_M")
    new_names <- c("Euler", "Milstein")
  }
  colnames(correlation_mat) <- c("Stan", method_order)
  
  correlation_mat[,1] <- resultsOverall[, "covariance"] / 
    sqrt(results_separate[, "variance", 1] * results_separate[, "variance", 1] )
  
  for(k in method_names){
    correlation_mat[,k] <- resultsOverall_all[, "covariance", k] / 
      sqrt(results_separate_all[, "variance", 1, k] * results_separate_all[, "variance", 1, k] )
  }
  colnames(correlation_mat) <- c("True posterior", new_names)
  correlation_mat
}

m <- 5
correlation_mat <- aggregated_correlations(obsFolder, M, m)


window_width <- 7
window_height <- 2.8


par(mar=c(4, 4.5, 2, 1))
layout.matrix <- matrix(c(1, 2, 4,
                          0, 3, 5), nrow = 2, ncol = 3, byrow = TRUE)
layout(mat = layout.matrix,
       heights = c( 2, 2), 
       widths = c(2, 2, 2)) 


for(k in 1:dim(correlation_mat)[2]){
  main <- dimnames(correlation_mat)[[2]][k]
  hist(correlation_mat[,k], 
       main = main, xlab = "",
       las = 1)
  title(xlab = "Parameter correlation", cex.lab = 1, line = 2)
}
```

